name: CI/CD для Telegram бота

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Кэширование зависимостей pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
        
    - name: Линтинг с flake8
      run: |
        # остановка сборки при наличии синтаксических ошибок Python
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # проверка с предупреждениями (не останавливает сборку)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
  deploy:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Настройка Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Вход в Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Получение версии
      id: vars
      run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)"
        
    - name: Сборка и публикация Docker образа
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/tg-bot:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/tg-bot:${{ steps.vars.outputs.tag }} 